export const products = [
  {
    description: `Shrink wrap`,
    src: "/images/white-rolled-plastic.jpeg",
    name: "Shrink wrap",
    type: "wrap",
  },
  {
    description: `Pure water nylon`,
    src: "/images/wrapped-rolled-plastic.jpeg",
    name: "Pure water nylon",
    type: "nylon",
  },
  {
    description: `Water`,
    src: "/images/water-bottle.jpeg",
    name: "water",
    type: "water",
  },
  {
    description: `Water 50cl`,
    src: "/images/pack-of-water.jpeg",
    name: "Water 50cl",
    type: "water",
  },
  {
    description: `Plastic`,
    src: "/images/yellow-plastic-bottle.jpeg",
    name: "Yellow plastic bottle",
    type: "plastic",
  },
  {
    description: `Plastic`,
    src: "/images/red-plastic-bottle.jpeg",
    name: "Red plastic bottle",
    type: "plastic",
  },
  {
    description: `4 liters keg (plastic)`,
    src: "/images/white-jerry-can.jpeg",
    name: "white jerry can",
    type: "plastic",
  },
  {
    description: `Plastic`,
    src: "/images/blue-jerry-can.jpeg",
    name: "Blue jerry can",
    type: "plastic",
  },
  {
    description: `Water 75cl`,
    src: "/images/pack-of-firstdrop-water.jpeg",
    name: "A back of firstdrop water bottle",
    type: "water",
  },
  {
    description: `Plastic`,
    src: "/images/standing-red-water-bottle.jpeg",
    name: "Red water bottle",
    type: "plastic",
  },
  {
    description: `Dispenser`,
    src: "/images/water-dispenser.jpeg",
    name: "Water dispenser bottle",
    type: "dispenser",
  },
  {
    description: `Plastic (1L keg)`,
    src: "/images/green-bottle.jpeg",
    name: "Green plastic keg",
    type: "plastic",
  },
  {
    description: `Plastic (Caps)`,
    src: "/images/bottle-caps.jpeg",
    name: "Bottle caps",
    type: "plastic",
  },
  {
    description: `Pure water`,
    src: "/images/pure-water.jpeg",
    name: "Sachet water",
    type: "pure-water",
  },
  {
    description: `Preforms`,
    src: "/images/white-test-tube.jpeg",
    name: "White test tubes",
    type: "preforms",
  },
  {
    description: `Plastic`,
    src: "/images/white-bottle.jpeg",
    name: "White bottle",
    type: "plastic",
  },
  {
    description: `Plastic (25L keg)`,
    src: "/images/yellow-jerry-can.jpeg",
    name: "Yellow jerry can",
    type: "plastic",
  },
  {
    description: `Preforms`,
    src: "/images/blue-test-tubes.jpeg",
    name: "Blue test-tubes",
    type: "preforms",
  },
  {
    description: `Plastic (Caps)`,
    src: "/images/grouped-caps.jpeg",
    name: "Bottle caps",
    type: "plastic",
  },

  {
    description: `PET bottle`,
    src: "/images/pet-bottle.jpeg",
    name: "PET bottle",
    type: "pet",
  },
  {
    description: `Plastic (Fork)`,
    src: "/images/plastic-forks.jpeg",
    name: "Plastic forks",
    type: "plastic",
  },
  {
    description: `Customer pet bottle`,
    src: "/images/white-kegs.jpeg",
    name: "Customer pet bottle",
    type: "pet",
  },
  {
    description: `Plastic (Spoon)`,
    src: "/images/plastic-spoons.jpeg",
    name: "Plastic spoons",
    type: "plastic",
  },
]
